### ISSUE TITLE
[BUG] [MC-VERSION] Short description of the bug

### ISSUE THREAD

**Issue by Katsunsama** [Exopandora/ShoulderSurfing#163] opened 2024-03-14 03:08 UTC
### Description

Crash on entry to server, 

### Steps to Reproduce

1. Play DawnCraft v2.0.1_f beta
2. Play on Dedicated Server
3. Unsure how to replicate from here-

### Expected Behavior

Be able to load into game... I crash on entry, Im going to try modifying my player data to move my character to see if a change in positioning fixes the issue, but I was last in a cave, so it's hard to say what caused the bug. 

### Game Logs

https://gist.github.com/Katsunsama/5c71c126b7f4cf458b0258b66e509411

**Comment by Exopandora** [comment] 2024-03-14 22:08
Thanks for the report. This is a duplicate of  #162.

**Closed by Exopandora** 2024-03-14 22:08 UTC
