### ISSUE TITLE
[1.12.2] Crosshair is missing

### ISSUE THREAD

**Issue by TCreopargh** [Exopandora/ShoulderSurfing#53] opened 2021-07-02 11:00 UTC
I just updated shoulder surfing to 2.1.1 and the crosshair is missing in 3rd person mode or shoulder surfing mode. Tried adjusting the options (including deleting the config) and still can't get the crosshair back.

**Comment by Exopandora** [comment] 2021-07-02 11:02
Please provide the resulting crash log from pressing `F3` + `C` for 10 seconds while ingame. If you are using any other mods it is very helpful if you can find the mod that causes the issue. The easiest method would be to split the list in half and figure out in which half the issze occurs. If you found the half, repeat the method again until you know which mod causes the issue.

**Comment by TCreopargh** [comment] 2021-07-02 11:16
This issue doesn't exist on 1.15.1

**Comment by Exopandora** [comment] 2021-07-02 11:18
Those versions are also very different in their implementation

**Comment by Exopandora** [comment] 2021-07-02 11:39
But i need more information from you if you want me to potentially fix this see.

**Comment by TCreopargh** [comment] 2021-07-04 10:25
optifine is installed and shaders are enabled. Idk if thats the reason. will send you the full mod list later

**Comment by Exopandora** [comment] 2021-07-04 11:43
I tested OptiFine and shaders and it should be fine. Please follow the steps from my first response:


> 
> 
> Please provide the resulting crash log from pressing `F3` + `C` for 10 seconds while ingame. If you are using any other mods it is very helpful if you can find the mod that causes the issue. The easiest method would be to split the list in half and figure out in which half the issue occurs. If you found the half, repeat the method again until you know which mod causes the issue.

**Comment by TCreopargh** [comment] 2021-07-04 15:25
Sorry I cant reach my computer rn, will update.the issue when I can

**Comment by TCreopargh** [comment] 2021-07-05 15:45
Crash log including the full mod list:
https://paste.ubuntu.com/p/RNCr22KGZ2/
Note: shoulder surfing in this list is v1.15.1 because I downed the version to fix this issue. This issue exists in v2.1.1 without other mod changes.
I don't have time to do the binary search today (I have 500+ mods and the last time when I did a binary search it took me a whole full day looking at the loading screen), but if I find the conflicting mod I will notify you.

**Comment by Exopandora** [comment] 2021-07-05 15:47
Are you using "Override Mod Crosshairs" in 1.12.2-1.15.1?

**Comment by TCreopargh** [comment] 2021-07-14 08:22
Can't reach my computer rn but iirc I tried to turn it off and nothing changed, will try again when I have time

**Comment by TCreopargh** [comment] 2021-07-14 14:57
Yes I'm using "Override Mod Crosshairs" in 1.15.1, turning it off in 2.1.2 does not fix this issue.

**Comment by Exopandora** [comment] 2021-07-14 15:01
2.1.2 does not have this option

**Comment by Exopandora** [comment] 2021-07-14 15:08
Could you also send me your latest.log (just after you booted the game)?

**Comment by TCreopargh** [comment] 2021-07-15 14:43
latest.log:
https://gist.github.com/TCreopargh/ad9760d75bb2da29ac9ba7e43b9206aa

**Comment by Exopandora** [comment] 2021-07-15 15:22
The log looks fine

**Comment by Exopandora** [comment] 2021-07-15 22:13
Did you try resetting the ssr config?

**Comment by TCreopargh** [comment] 2021-07-16 02:11
Yes I tried deleting the config, doesn't work

**Comment by Exopandora** [comment] 2021-07-17 18:12
Have you tried without a shaderpack enabled or without optifine alltogether? It should not cause the problem but it might be worth checking anyways. Otherwise a binary search would be the only way to move forward

**Comment by TCreopargh** [comment] 2021-07-20 06:30
Thanks, will try when I get time

**Comment by TCreopargh** [comment] 2021-07-21 14:56
Just tried removing optifine, nope, doesn't work

**Comment by ainlzj** [comment] 2021-08-10 19:10
ME to

**Comment by Exopandora** [comment] 2021-08-10 19:14
> 
> 
> ME to

As i already said. Without a conrete name of the mod that causes the issue i am not able to do anything about it.

**Comment by ainlzj** [comment] 2021-08-13 02:38
> > ME to
> 
> As i already said. Without a conrete name of the mod that causes the issue i am not able to do anything about it.
1.12.2 The reason for the disappearance of the pointer has been found. It is caused by the addition of BetterCombat, but I have a little doubt. I remember that there was no such problem before.

**Comment by ainlzj** [comment] 2021-08-13 02:43
> > 我去
> 
> 我已经说过了。 没有实际的名字国防部导致这个问题我无法做任何事情。

1.12.2 The reason for the disappearance of the pointer has been found. It is caused by the addition of BetterCombat, but I have a little doubt. I remember that there was no such problem before.

**Comment by ainlzj** [comment] 2021-08-13 02:44
> > ME to
> 
> As i already said. Without a conrete name of the mod that causes the issue i am not able to do anything about it.

1.12.2 The reason for the disappearance of the pointer has been found. It is caused by the addition of BetterCombat, but I have a little doubt. I remember that there was no such problem before.

**Comment by Exopandora** [comment] 2021-08-14 15:14
Fixed in the latest version

**Closed by Exopandora** 2021-08-14 15:14 UTC
