### ISSUE TITLE
Incompatible with Iris

### ISSUE THREAD

**Issue by kyber-6** [Exopandora/ShoulderSurfing#219] opened 2024-06-22 12:29 UTC
### Description

This incompatibility issue began occurring when Iris started to add Distant Horizons support. With certain shaders, the player armour is transparent.

In this image, I am wearing full Netherite armour.

![2024-06-22_14 26 58](https://github.com/Exopandora/ShoulderSurfing/assets/100732009/f93a4e0e-251e-4061-a4f9-06d2cd2998d2)

### Minecraft version

1.20.1

### Incompatible mod name

Iris

### Incompatible mod version

1.7.1

### Game Logs

https://mclo.gs/iuzTmEY

**Comment by Exopandora** [comment] 2024-06-22 14:20
Duplicate of #199. The player transparency adjustment feature of Shoulder Surfing Reloaded needs support from the respective shader pack. Consider reporting this to the authors of said shader pack. As a workaround, you could consider setting `adjust_player_transparency` in the config of Shoulder Surfing Reloaded to `false` (don't forget to restart your game).

**Closed by Exopandora** 2024-06-22 14:20 UTC
Labels: compatibility
