### ISSUE TITLE
Crash on world creation or when you load into one

### ISSUE THREAD

**Issue by SouthernPixel** [Exopandora/ShoulderSurfing#32] opened 2020-12-30 04:42 UTC
https://paste.gg/p/anonymous/5be8243d9d7243a2b1bb200f8a9199aa There is the crash report. Should I provide the debug.log as well?

**Comment by Exopandora** [comment] 2020-12-30 13:15
Duplicate of #31

**Closed by Exopandora** 2020-12-30 13:15 UTC
