### ISSUE TITLE
Invinsible Armor And Character Photon Shader With ShoulderSurfing

### ISSUE THREAD

**Issue by CaoTrongThang** [Exopandora/ShoulderSurfing#250] opened 2024-10-21 13:59 UTC
### Description

My armos and character are invisible, and mostly look like a bug.

### Steps to Reproduce

Downloaded The Mod
Ran It With Photon Shader

### Minecraft version

1.20.10

### Game Logs

https://mclo.gs/G2idqCK

### Additional Information
I really hope you can fix this, Photon shader is really good with Patrix texture pack and your ShoulderSurfing mod, it really brings the perfect vibe for the modpack.

![image](https://github.com/user-attachments/assets/f584cd45-2ee7-4447-b688-ba154999a08f)
![image](https://github.com/user-attachments/assets/b839ddbe-3ac4-498c-ae51-642a53b93389)

All the armors I used Enchanted Iron Helmet, Enchanted Iron Plate, Chainmail Leggings, Chainmail Boots
![image](https://github.com/user-attachments/assets/c9fafeac-9d12-4445-9b23-e827515c15b0)

**Comment by Exopandora** [comment] 2024-10-21 15:55
Duplicate of #219 and #199. Please refer to the [FAQ](https://github.com/Exopandora/ShoulderSurfing?tab=readme-ov-file#faq) section or [this](https://github.com/Exopandora/ShoulderSurfing/issues/219#issuecomment-2184051358) comment for a workaround.

**Closed by Exopandora** 2024-10-21 15:55 UTC
Labels: bug
