### ISSUE TITLE
[BUG] [1.19.2 Forge] - conflict with the modification of "CameraOverhaul"

### ISSUE THREAD

**Issue by LEXi04ka** [Exopandora/ShoulderSurfing#102] opened 2023-01-03 00:27 UTC
### Description

"Shoulder Surfing Reloaded" makes the third-person view shifted, that is, the view is not directly over the head (as in vanilla), but next to the shoulder.
modification of "CameraOverhaul" makes the camera dynamic (it tilts depending on the situation)

conflict: the third-person view shifts to the original one (not the shoulder, but above the head), continues to be shifted at the crosshair, which is why the blows directly mow to the side.

is there any way to solve this? I want to play with these two modifications, but because of bugs it is problematic

(and I apologize in advance for possible errors in the text - I'm with the translator)

### Steps to Reproduce

1.Install "Shoulder Surfing Reloaded"
2. Install "CameraOverhaul"
3. Log into the game and turn on the view from the modified 3rd person.
4. done- bug

### Expected Behavior

so that the crosshair is (as it should be) next to the shoulder, and so that the modification to the dynamic camera works

### Screenshots

![image](https://user-images.githubusercontent.com/104824481/210286797-30d1ccfd-8516-4ff9-8061-97b287332554.png)

![image](https://user-images.githubusercontent.com/104824481/210286805-d4d022cd-5056-4da8-8adc-51ab1b22547d.png)

### Game Logs
https://pastebin.com/D8KQxGq0

**Comment by Exopandora** [comment] 2023-01-06 23:00
I tested with camera overhaul and shoulder surfing installed at the same time. The issue did not occur. It must be caused by another mod or it is caused by a configuration error. Tip: You might get a better translation using [DeepL Translator](https://www.deepl.com/translator).

**Comment by Exopandora** [comment] 2023-01-06 23:01
Also: Please use https://gist.github.com for posting logs

**Comment by LEXi04ka** [comment] 2023-01-12 13:41
Oh, deepl. never heard of such a thing. yes, it is undoubtedly better!
and... what? how is it wrong? i myself now run with and without "CameraOverhaul". with it - the crosshairs move to the center, and without - everything is fine. 

I don't know how to throw screenshots in the comments here to show this.
In my folder right now:
1. "Shoulder Surfing Reloaded" - new 3rd person view (behind the shoulder)
2. "BetterThirdPerson-Forge"-improved 3-person view (the camera is not tied to the direction of sight directly)


As soon as I add a 3rd "CameraOverhaul" - everything breaks, as in the pictures above. 

By the way...
maybe I'm wrong about something and the problem is not in your mod, can you take a look please?

**Comment by Exopandora** [comment] 2023-01-12 18:59
As you can see in this video, it works without issue. Did you test it with just shoulder surfing and cameraoverhaul installed? That means, without any other mods?

https://user-images.githubusercontent.com/18708736/212156761-ff0238c7-e022-451a-bb89-2fd206701d72.mp4

**Comment by LEXi04ka** [comment] 2023-01-14 15:22
Yes, you're right. I double-checked it and it turns out that the problem is not with "CameraOverhaul". or rather, partially. 
Separately modifications work fine, but it is necessary to collect in one place at once 3 mods: 
1.Shoulder Surfing Reloaded
2.CameraOverhaul
3.BetterThirdPerson
As arises the above error

**Comment by Exopandora** [comment] 2023-01-14 17:43
I tested again with BetterThirdPerson installed additionally and it also works as intended. In the original error log you sent, there are numerous errors for BetterThirdPerson. Your issue might be caused by another mod that breaks BetterThirdPerson.

**Comment by Exopandora** [comment] 2023-03-04 15:10
Any update on this? Otherwise i would close this issue.

**Comment by amoooooo** [comment] 2023-03-06 00:10
I've had this issue too but I could not figure out what caused it. There are a number of popular mods that could mess with this, but it @LEXi04ka could post their mod list and i can cross compare we'd be able to find it i bet.

**Comment by Exopandora** [comment] 2023-03-19 11:40
@amoooooo thanks for trying to help. The modlist can be found in the logs.

**Comment by JasonFreeVT** [comment] 2023-06-07 21:13
I was curious as to what was causing this too, since I was experimenting with client-side mods. It seems that it's specifically the interaction between Camera Overhaul and Better Third Person that's causing this bug, but only with the 1.90 version of Better Third Person. The 1.81 version seems to work fine with everything else.

**Comment by Exopandora** [comment] 2024-04-09 17:42
Closing this, as CameraOverhaul is no longer supported in Shoulder Surfing Reloaded version 3.0.0+.

**Closed** 2024-04-09 17:42 UTC
