### ISSUE TITLE
[Suggestion] add a config to completely remove the third person back and front perspective

### ISSUE THREAD

**Issue by memphismc** [Exopandora/ShoulderSurfing#229] opened 2024-07-13 11:00 UTC
as the title suggests, i want only the first person and shoulder surfing perspective so that when im in first person and i press f5 i jump directly to the shoulder surfing perspective

**Comment by Exopandora** [comment] 2024-07-13 11:53
Duplicate of #17

**Closed by Exopandora** 2024-07-13 11:53 UTC
Labels: feature
