### ISSUE TITLE
Incompatible with AutoHUD

### ISSUE THREAD

**Issue by dandy-is-lion** [Exopandora/ShoulderSurfing#256] opened 2024-11-29 04:02 UTC
### Description

AutoHUD hides different elements on your HUD, from the hotbar to the crosshair. When disabling its interaction with the crosshair (setting Crosshair > Active = False), it causes an interesting effect when Shoulder Surfing's crosshair is set to dynamic or adaptive and you hold a shooting weapon, like a bow or snowball. It causes the entire HUD to move with it, and the crosshair doesn't display, throwing up errors in the log. Reenabling AutoHUD's interaction with the crosshair (setting Crosshair > Active = True) removes this glitch.

Tested in a minimal instance in the log below.

![2024-11-28_21 41 25](https://github.com/user-attachments/assets/1de4c46c-9ce1-48ec-b926-43e954dbc6f2)

### Minecraft version

1.20.1-FORGE-47.3.6

### Incompatible mod name

AutoHUD

### Incompatible mod version

8.0

### Game Logs

https://mclo.gs/9GNiRFt

**Comment by Exopandora** [comment] 2024-11-29 19:35
Thanks for reporting. I pushed a fix for the "offset hud" bug. The error messages in the logs are caused by AutoHUD, which also appear when you just install AutoHUD on its own. It looks like they are targeting newer or older code than 1.20.1. Because of that, the crosshair still behaves a bit buggy. I suggest reporting this to the authors to AutoHUDin order to fully fix the issue.

**Closed** 2024-11-29 19:54 UTC
Labels: compatibility
