### ISSUE TITLE
Input lag bug

### ISSUE THREAD

**Issue by JupiterSky11** [Exopandora/ShoulderSurfing#45] opened 2021-05-22 22:30 UTC
For some reason when I press an input related to the mod it is delayed a decent bit, I've also noticed that the adjustment keys are super buggy.  (Latest release.)

**Comment by Exopandora** [comment] 2021-05-22 22:32
Please provide the resulting crash log from pressing `F3` + `C` for 10 seconds while ingame.

**Comment by JupiterSky11** [comment] 2021-05-22 22:54
[crash-2021-05-22_18.50.47-client.txt](https://github.com/Exopandora/ShoulderSurfing/files/6527281/crash-2021-05-22_18.50.47-client.txt)

**Comment by JupiterSky11** [comment] 2021-05-22 23:53
After a bit of experimenting, I've found that the delayed input updates when normal input is used, and also after a certain period of time.
The glitchy adjustment is still strange though.

**Comment by Exopandora** [comment] 2021-05-23 14:52
Do you know how to build from source?

**Comment by Exopandora** [comment] 2021-05-23 21:54
I have spotted some issues regarding keybinds glitching out. This should be fixed in the latest commit. If you know how to build from source you can try it out and see if it fixes your issue. Though i was not able to reproduce your "delayed input".

To build from source run the following commands in a terminal:
`git clone https://github.com/Exopandora/ShoulderSurfing.git`
`cd ./ShoulderSurfing`
`gradlew build`

The jar should be located in `./build/libs/`

**Comment by JupiterSky11** [comment] 2021-05-26 09:01
Fantastic, it works wonderfully!  The weird delay seems to only be an issue with this mod and my mouse.
Oh yeah, there's is a bit of a flickering sometimes, my framerate is rather high so it might be that.
Thank you for the quick response and prompt bugfix!

**Comment by Exopandora** [comment] 2021-05-26 12:04
Regarding the flickering: Did you press the buttons in any special pattern?

**Comment by Exopandora** [comment] 2021-05-26 12:17
I dont think that its a frame rate related issue though, as i get up to 600fps and did not encounter any flickering. It might be caused by different file observing behaviours of linux (your setup) and windows (my setup). When the system detects a file change it will automatically reload the config file. Maybe that sometimes resets the values to an earlier state, causing the flickering.

**Comment by JupiterSky11** [comment] 2021-05-26 22:59
That's more likely the issue.  I didn't do anything particular, it just happens when I use the adjustment keys.  It's really noticeable when you hold it down, but it's nothing so bad that it breaks the function of the mod.

**Comment by Exopandora** [comment] 2021-05-27 12:09
I made some more changes and i'm fairly confident it will be fully fixed this time. Again though you need to build from source in order to test it. If you still have the repo from the previous build you can simply run the following commands in `./ShoulderSurfing/` to get the updated version:
`git pull`
`./gradlew build`

The jar will again be located in `./build/libs/`

**Comment by Exopandora** [comment] 2021-06-02 09:01
A release version is now available on curseforge

**Comment by JupiterSky11** [comment] 2021-06-02 09:14
Yep, works fine.  Flickering is better for the most part, but it still happens from time to time.  Everything else is fixed though!
Glad I could help out, this is a good mod that I very much enjoy.

**Comment by Exopandora** [comment] 2021-06-02 10:16
What exact linux distro are you using? And what type of drive (hdd/ssd) are you using?

**Comment by JupiterSky11** [comment] 2021-06-02 22:57
Ubuntu, and an NVMe SSD.

**Closed** 2022-08-02 23:21 UTC
