### ISSUE TITLE
Incompatible with Lock On

### ISSUE THREAD

**Issue by simon-arch** [Exopandora/ShoulderSurfing#259] opened 2024-12-29 20:07 UTC
### Description

Using decoupled camera mode with lock on results in violent spinning.
I'd guess this happens because Lock On expects the player's entire body to rotate, not only the camera.
Spinning is gone when decoupled camera mode is off.
Maybe the best solution would be forcefully turning off decoupled camera mode on lock on?

Tested on a separate new CurseForge profile.

With decoupled camera mode on:
![with_deco](https://github.com/user-attachments/assets/7f0727f5-a231-4db5-bf30-f19fd496f74a)

With decoupled camera mode off:
![no_deco](https://github.com/user-attachments/assets/c06b0b8b-429f-41f8-8399-a4146170ceee)

### Minecraft version

1.20.1

### Incompatible mod name

Lock On [Fabric]

### Incompatible mod version

1.0.1

### Game Logs

https://mclo.gs/1TCSYTo

**Comment by Exopandora** [comment] 2024-12-29 22:03
Thanks for the report. This is a duplicate of #195.

**Closed** 2024-12-29 22:03 UTC
Labels: compatibility

**Comment by TENKAIS** [comment] 2025-04-29 19:35
How can i put headlock mode?
