### ISSUE TITLE
Toggling Perspective temporarily removes the mod until launcher restarted

### ISSUE THREAD

**Issue by Egolfius** [Exopandora/ShoulderSurfing#26] opened 2020-08-17 00:24 UTC

**Comment by Exopandora** [comment] 2020-08-17 00:43
Please provide the resulting crash log from pressing `F3` +`C` for 10 seconds while ingame and give a detailed description of how to reproduce the issue.

**Comment by Egolfius** [comment] 2020-08-17 21:59
Ok here's the crash log. 

I start out in shoulder surfing 3rd person. After pressing f5 once, I enter first person. After pressing it again, I enter normal 3rd person rear view. After pressing it a third time, I enter third person front view. After pressing it a 4th time I return to first person. Any further f5 pressing cycles threw first person, rear, front.

Basically, once I change perspectives with f5 I'm never able to return to shoulder surfing.

`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/17/20, 5:54 PM
Description: Manually triggered debug crash

java.lang.Throwable: null
	at net.minecraft.client.KeyboardListener.func_204870_b(KeyboardListener.java:428) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1504) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:928) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.1-forge-32.0.108.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.1-32.0.108.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.KeyboardListener.func_204870_b(KeyboardListener.java:428)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Egolfius'/233, l='ClientLevel', x=-190.07, y=64.00, z=-25.49]]
	Chunk stats: Client Chunk Cache: 1369, 1013
	Level dimension: minecraft:overworld
	Level spawn location: World: (-160,64,-128), Chunk: (at 0,4,0 in -10,-8; contains blocks -160,0,-128 to -145,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 8752 game time, 8752 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:446)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:598)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 5.3.0-28-generic
	Java Version: 11.0.8, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 697214232 bytes (664 MB) / 1442840576 bytes (1376 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.108.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.108
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.108-client.jar Minecraft {minecraft@1.16.1 DONE}
		forge-1.16.1-32.0.108-universal.jar Forge {forge@32.0.108 DONE}
		torohealth-1.16.1-forge-2.jar ToroHealth {torohealth@NONE DONE}
		Xaeros_Minimap_20.20.0_Forge_1.16.1.jar Xaero's Minimap {xaerominimap@20.20.0 DONE}
		ShoulderSurfing-1.16.1-1.23.jar Shoulder Surfing {shouldersurfing@1.16.1-1.23 DONE}
	Launched Version: 1.16.1-forge-32.0.108
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Mesa DRI Intel(R) UHD Graphics (CML GT2) GL version 3.0 Mesa 20.0.8, Intel Open Source Technology Center
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz`

**Comment by Exopandora** [comment] 2020-08-17 22:40
I can't reproduce your issue. Did you change any config settings ?

**Comment by Egolfius** [comment] 2020-08-19 00:07
I didn't. Is there anything else that could be different between our installs? I have the same issue on two different machines. One is ubuntu and one is windows. I suppose they're both using the same forge install?

**Comment by Exopandora** [comment] 2020-08-19 00:17
The only difference i can see is that you are using java 11 and not java 8 which is bundled with the game (also open jdk instead of oracle). I will test it again on my machine tomorrow with default settings and a newer java version.

**Comment by Exopandora** [comment] 2020-08-19 09:50
So i tested it again with default settings and the problem did not surface. I tried to launch with java 14 but the game does not launch. I also wanted to test java 11 as it is the version that you are using but its not available for download anymore. I was testing with forge 1.16.1-32.0.108 and shoulder surfing 1.16.1-1.23 on windows 10 and bundled jre. Did you change the config to replace the default 3pp ?

**Comment by Exopandora** [comment] 2020-08-27 20:16
This issue should be fixed for 1.16.2 as the system required a rewrite due to changes made by mojang

**Closed** 2021-01-11 20:49 UTC
