### ISSUE TITLE
[BUG] [1.19.3] Dynamic Crosshair Incompatibility with Exordium

### ISSUE THREAD

**Issue by karpandsmeargle** [Exopandora/ShoulderSurfing#117] opened 2023-05-09 18:19 UTC
### Description

Dynamic crosshair remains static when Exordium "Enable Gui" feature is turned on. Works with this feature off.

https://github.com/tr7zw/Exordium 

### Steps to Reproduce

1. Load into a game with both Exordium and ShoulderSurfingReloaded
2. Turn on shoulder surfing mode

### Expected Behavior

Dynamic crosshair should not be static

### Game Logs

https://gist.github.com/karpandsmeargle/074c0dae40fa6c71b2718884529897fb

### Other Mods

Exordium 1.0.3-mc1.19.3

**Comment by Exopandora** [comment] 2023-05-09 21:45
I suggest forwarding this to the author of Exordium. They could either check if SSR is installed and accordingly or provide a config option to specifically enable/disable frame rate limiting for crosshairs. To elaborate a bit on the actual cause of the issue: Exordium cancels crosshair rendering when "Enable Gui" is set to true, disabling the code of SSR.

**Comment by Exopandora** [comment] 2024-04-01 12:43
Closing this for now, as the issue is not caused by SSR.

**Closed by Exopandora** 2024-04-01 12:43 UTC
